ip4: 10.130.0.253
ip6: 2001:67c:2d50::c01
ip6_ula: fdef:ffc0:3dd7::c01
fastd_mac: d6:89:49:08:f6:9d
fastd_mac_2: ce:69:95:f0:a9:53
fastd_gw_mac: d6:89:49:08:f6:9e
freifunk_mac: 52:54:00:0c:bb:eb
dhcpd_start: 10.130.4.191
dhcpd_end: 10.130.8.126
snat_dev: ffrhein-+
snat_ip4: 185.66.193.33
icvpn_name: luebeck1
icvpn_ip4: 10.207.0.130
icvpn_ip6: fec0::a:cf:0:82
units_enable:
  - "'fastd@dn42\\x2dchaos.service'"
