ip4: 10.130.0.254
ip6: 2001:67c:2d50::a01
ip6_ula: fdef:ffc0:3dd7::a01
fastd_mac: 26:9c:57:9b:5c:b2
fastd_mac_2: 6a:0a:8d:97:50:69
fastd_gw_mac: 26:9c:57:9b:5c:b3
freifunk_mac: de:ad:ca:fe:46:1d
dhcpd_start: 10.130.8.127
dhcpd_end: 10.130.12.62
units_enable:
